# Etapa 1: Build
FROM node:22-alpine AS builder

WORKDIR /app

# Copiar package.json primero para cache
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Compilar TypeScript
RUN npm run build

# Etapa 2: Runtime
FROM node:22-alpine

WORKDIR /app

# Copiar solo lo necesario
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

ENV PORT=${PORT}
EXPOSE ${PORT}

CMD ["node", "dist/app.js"]
